# Config
font=JetBrains Mono NF:size=12,Apple Color Emoji:size=12
line-height=15

# Catppuccin
[colors-dark]
background=1e1e2e
foreground=cdd6f4
cursor=1e1e2e f5e0dc

regular0=1e1e2e
regular1=f38ba8
regular2=a6e3a1
regular3=f9e2af
regular4=89b4fa
regular5=cba6f7
regular6=74c7ec
regular7=bac2de

bright0=585b70
bright1=eba0ac
bright2=94e2d5
bright3=f9e2af
bright4=b4befe
bright5=f5c2e7
bright6=89dceb
bright7=cdd6f4

16=fab387
17=f5e0dc

selection-foreground=1e1e2e
selection-background=f5e0dc

search-box-no-match=1e1e2e a6adc8
search-box-match=1e1e2e a6e3a1

jump-labels=1e1e2e f9e2af
urls=89b4fa

