# Nvidia
LIBVA_DRIVER_NAME=nvidia
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
__GL_SHADER_DISK_CACHE_PATH=/home/wojtek/.cache/nv

# Wayland
XDG_SESSION_TYPE=wayland
WLR_NO_HARDWARE_CURSORS=1

# Qt
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=qt6ct
QT_STYLE_OVERRIDE=kvantum

# Inne
_JAVA_AWT_WM_NONREPARENTING=1
TERMINAL=foot
XDG_MENU_PREFIX=arch-
XCURSOR_SIZE=24
HYPRCURSOR_SIZE=24
